<?php 
return array (
  'HOME_URL'      => 'www.mall.com',
  'CHANNEL_URL'   => 'channel.mall.com',
  'LIST_URL'      => 'list.mall.com',
  'DETAIL_URL'    => 'detail.mall.com',
  'ABOUT_URL'     => 'about.mall.com',
  'USER_URL'      => 'i.mall.com',
  'PASSPORT_URL'  => 'passport.mall.com',
  'OAUTH_URL'     => 'oauth.mall.com',
  'REG_URL'       => 'register.mall.com',
  'CART_URL'      => 'cart.mall.com',
  'ADVERT_URL'    => 'advert.mall.com',
  'ADMIN_URL'     => 'admin.mall.com',
  'APP_SUB_DOMAIN_DEPLOY'         =>          1,
  'APP_SUB_DOMAIN_RULES'          =>          array(
      'www'       =>  array('Home/'),
      'channel'   =>  array('Channel/'),
      'list'      =>  array('List/'),
      'detail'    =>  array('Detail/'),
      'cart'      =>  array('Cart/'),
      'i'         =>  array('User/'),
      'passport'  =>  array('User/login','a=login'),
      'oauth'     =>  array('Oauth/'),
      'register'  =>  array('User/login','a=register'),
      'about'     =>  array('About/'),
      'advert'     =>  array('Advert/'), 
      'admin'     =>  array('Admin/'), 
  ),
);